### ISSUE TITLE
__assert_fail linking error with OMPTARGET

### ISSUE THREAD

**Issue by meifeng** [BNL-HPC/Grid#4]
`clang++ -I/global/u1/m/meifeng/ECP/Grid-fork/Grid    -O3 -Wno-unknown-cuda-version -I/usr/common/software/sles15_cgpu/cuda/11.0.3/include -fopenmp -std=c++14 -fopenmp-cuda-mode  -O3 -g -fopenmp-targets=nvptx64-nvidia-cuda -Wformat -DOMPTARGET -DOMPTARGET_MANAGED  -fno-strict-aliasing -L/global/u1/m/meifeng/ECP/Grid-fork/Grid/build-cgpu/Grid   -L/usr/common/software/sles15_cgpu/cuda/11.0.3/lib64 -lcudart -o Benchmark_dwf Benchmark_dwf.o ../Grid/libGrid.a -lz -lcrypto -lmpfr -lgmp -lm  -lz
nvlink error   : Undefined reference to '__assert_fail' in '/tmp/Benchmark_dwf-ab88c5.cubin'
/global/project/projectdirs/m1759/csdaley/software/cgpu/llvm/14.0.0-git_20211104b/bin/clang-nvlink-wrapper: error: 'nvlink' failed`

**Comment by atif4461** [comment]
Error does not appear on lambda2 with Eigen-3.4.0 and -DEIGEN_NO_CUDA.
